import os
import subprocess
import requests
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from github import Github

# Load environment variables from .env
load_dotenv()

# Verify Gemini API key
api_key = os.getenv("GOOGLE_API_KEY")
if not api_key or "YOUR_COPIED_GEMINI_KEY" in api_key:
    print("⚠️  WARNING: GOOGLE_API_KEY is missing in your .env file.")

# Use Gemini 1.5 Flash (latest version to avoid 404 errors)
llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash-latest", temperature=0)

def run_pytest():
    """Runs local pytest suite and captures standard output/error."""
    result = subprocess.run(["pytest", "Target_app/test_app.py"], capture_output=True, text=True)
    return result.returncode == 0, result.stdout + result.stderr

def fix_code_with_llm(error_logs):
    """Reads buggy code and feeds error log to Gemini for patch generation."""
    with open("Target_app/app.py", "r") as f:
        code = f.read()
    
    prompt = f"""
Existing Code:
{code}

Pytest Error Logs:
{error_logs}

Fix the code in Target_app/app.py so that all pytest assertions pass.
IMPORTANT: Return ONLY valid Python code. Do NOT include markdown formatting or backticks.
"""
    try:
        response = llm.invoke(prompt)
        clean_code = response.content.replace("```python", "").replace("```", "").strip()
        
        with open("Target_app/app.py", "w") as f:
            f.write(clean_code)
        print("🛠️  Self-healing patch applied to Target_app/app.py via Gemini!")
    except Exception as e:
        print(f"\n❌ Gemini API Error: {e}")
        raise e

def send_slack_notification(pr_url, attempts):
    """Sends notification payload via Slack Webhook upon fix completion."""
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url or "YOUR/COPIED/URL" in webhook_url:
        print("📢 [Slack Integration] Mock Alert Sent: Incident resolved successfully!")
        return
    
    payload = {
        "text": f"🚨 *Sentry Incident Auto-Remediated*\n• *Engine*: Gemini 1.5 Flash\n• *Status*: Pytest Passed ✅\n• *Retries*: {attempts}\n• *GitHub PR*: {pr_url}"
    }
    try:
        requests.post(webhook_url, json=payload)
        print("📢 [Slack Integration] Live report posted to Slack channel!")
    except Exception as e:
        print(f"⚠️  Slack webhook error: {e}")

def create_github_pr():
    """Creates a real GitHub PR with the fixed code, or mocks it if token is missing."""
    github_token = os.getenv("GITHUB_TOKEN")
    
    if not github_token or "your_github" in github_token:
        print("🐙 [GitHub Integration] Token missing. Mock PR Created: https://github.com/org/repo/pull/101")
        return "https://github.com/org/repo/pull/101"
    
    try:
        g = Github(github_token)
        repo = g.get_repo("Dhruv2020-code/Multi-app-ai-agent")
        
        # Create a new branch
        source_branch = repo.get_branch("main")
        new_branch_name = f"ai-fix-bug-{os.urandom(4).hex()}"
        repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=source_branch.commit.sha)
        
        # Read the newly fixed code
        with open("Target_app/app.py", "r") as f:
            new_code = f.read()
            
        # Commit the fixed file to the new branch
        file_contents = repo.get_contents("Target_app/app.py", ref="main")
        repo.update_file(
            file_contents.path, 
            "🤖 AI Auto-Fix: Resolved failing tests in app.py", 
            new_code, 
            file_contents.sha, 
            branch=new_branch_name
        )
        
        # Open the Pull Request
        pr = repo.create_pull(
            title="🚨 Auto-Remediation: Bug Fix by Gemini AI",
            body="This PR was automatically generated by the AI Remediation Agent to fix failing Pytest assertions.",
            head=new_branch_name,
            base="main"
        )
        print(f"🐙 [GitHub Integration] Real PR Created Successfully: {pr.html_url}")
        return pr.html_url
    except Exception as e:
        print(f"❌ GitHub PR Failed: {e}")
        return "https://github.com/Dhruv2020-code/Multi-app-ai-agent/pulls"

def run_agent_loop(max_retries=3):
    """Main execution function called by Dashboard and Webhook."""
    print("🤖 Gemini AI Remediation Agent Loop Started...\n" + "="*50)
    
    for attempt in range(1, max_retries + 1):
        passed, logs = run_pytest()
        
        if passed:
            print(f"\n✅ VERIFICATION PASSED: All tests green on attempt {attempt}!")
            pr_url = create_github_pr()
            send_slack_notification(pr_url, attempt)
            print("="*50 + "\n🎉 Incident lifecycle completed autonomously.")
            return pr_url
        
        print(f"❌ Test Failed (Attempt {attempt}/{max_retries}). Generating patch...")
        fix_code_with_llm(logs)
        
    print("\n❌ Max retry limit reached.")
    return None

# Backward compatibility alias
start_agent_loop = run_agent_loop

if __name__ == "__main__":
    run_agent_loop()